//firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtqmAMHTBsyJUUu3M7H3PAsfKKIZ7DPxo',
    appId: '1:42044841546:web:138a47c2887e23ba9290b3',
    messagingSenderId: '42044841546',
    projectId: 'fir-smartpoo-c7613',
    authDomain: 'fir-smartpoo-c7613.firebaseapp.com',
    storageBucket: 'fir-smartpoo-c7613.appspot.com',
    measurementId: 'G-FCN2FLM3M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1S5AkICbJDG68XrYXiCbuqErLDo_4ms',
    appId: '1:42044841546:android:b86d2f006452fd279290b3',
    messagingSenderId: '42044841546',
    projectId: 'fir-smartpoo-c7613',
    storageBucket: 'fir-smartpoo-c7613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1D370FJLVitZyYtauYKOKYVQoSBGLtc',
    appId: '1:42044841546:ios:77eb54790884e01d9290b3',
    messagingSenderId: '42044841546',
    projectId: 'fir-smartpoo-c7613',
    storageBucket: 'fir-smartpoo-c7613.appspot.com',
    iosBundleId: 'com.example.firebaseSmartpoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1D370FJLVitZyYtauYKOKYVQoSBGLtc',
    appId: '1:42044841546:ios:77eb54790884e01d9290b3',
    messagingSenderId: '42044841546',
    projectId: 'fir-smartpoo-c7613',
    storageBucket: 'fir-smartpoo-c7613.appspot.com',
    iosBundleId: 'com.example.firebaseSmartpoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtqmAMHTBsyJUUu3M7H3PAsfKKIZ7DPxo',
    appId: '1:42044841546:web:0eddc993517c899f9290b3',
    messagingSenderId: '42044841546',
    projectId: 'fir-smartpoo-c7613',
    authDomain: 'fir-smartpoo-c7613.firebaseapp.com',
    storageBucket: 'fir-smartpoo-c7613.appspot.com',
    measurementId: 'G-RXKB8S3DFW',
  );
}
